chatgpt:
  prompt_template: "chatgpt/basic_prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "mistralai/mistral-7b-instruct:free"
    max_tokens: 50
    temperature: 0
    requires_chatml: True
  completion_parser_kwargs:
    outputs_to_match:
      1: '(?:^|\n) ?Output \(a\)'
      2: '(?:^|\n) ?Output \(b\)'
  batch_size: 1
